import { $, $$ } from "./dom.js";
const notes = {
  rules: [["产品选择", "页面标题 > 当前产品", "可按产品名称、型号或标识符搜索。切换后，规则、来源和多语言内容一起切换。", "product-switcher"], ["统一多语言", "页面标题 > 统一多语言", "两类推送共用 KV 大表。导入、语言勾选和内容均先保留在草稿，保存才应用。", "product-language-entry"], ["规则类型筛选", "推送规则 > 筛选区", "同一列表展示普通推送与汇总推送；已创建规则不支持直接切换类型。", "filter-bar"], ["规则列表", "推送规则 > 表格", "普通推送展示触发和频控；汇总推送展示汇总条件数量、每日发送时间和投递摘要。", "rules-table"], ["后续版本", "推送规则 > 后续能力", "事件择优、跨天维护预告、动态补项和通用 merge 不在本期范围。", "future-scope"]],
  typeChooser: [["规则类型", "新建推送规则 > 类型选择", "普通推送用于一次触发一条消息；汇总推送由一条完整规则拥有消息文案和汇总条件。创建后不能直接切换，避免隐式丢失配置。", "typeDialogTitle"]],
  rule1: [["步骤条", "规则抽屉 > 顶部", "按消息内容、触发条件、投递设置完成普通推送配置。", "step-nav"], ["消息内容", "步骤 1 > English 内容", "Title、Body 支持现有占位符；预设页面决定点击消息后的去向。", "placeholder-panel"], ["消息预览", "步骤 1 > 发送效果", "普通推送的 App 列表和详情显示同一套 Title / Body。", "message-previews"]],
  rule2: [["三类触发", "步骤 2 > 触发源", "设备触发选择物模型；云端选择云计时器；耗材选择配置好的耗材项。", "trigger-source"], ["物模型选择", "步骤 2 > 物模型", "搜索属性或事件。属性根据数据类型切换条件组件；事件固定为 = true。", "property-selector"], ["提醒时间", "步骤 2 > 提醒时间", "默认全天可提醒；需要限制时再指定时段，支持跨日。", "trigger-time"], ["接收者", "步骤 2 > 接收者", "只发给触发设备的绑定用户；无绑定用户时不发送。", "recipient-resolution"]],
  rule3: [["投递目标", "步骤 3 > 投递目标", "App 消息中心必选；系统 notification 可以按规则开启。", "delivery-target"], ["发送方式", "步骤 3 > 发送方式", "普通推送支持逐条发送和仅发送首条；仅发送首条才设置最小发送间隔。", "delivery-mode"], ["保存检查", "步骤 3 > 发布检查", "发布时检查 English、物模型条件和最小发送间隔。", "validation"]],
  rule1summary: [["步骤条", "汇总推送抽屉 > 顶部", "汇总推送也是完整规则，不依赖普通推送成员关系。", "step-nav"], ["消息内容", "步骤 1 > English 内容", "汇总规则直接拥有 Title / Body，只可使用设备和账号级稳定占位符。", "placeholder-panel"], ["三种预览", "步骤 1 > 发送效果", "系统 notification、App 列表和 App 详情均只显示同一套 Title / Body，不展示汇总条件。", "message-previews"]],
  rule2summary: [["汇总条件", "步骤 2 > 汇总范围", "每个条件只定义预测对象和命中条件，支持云计时器和云端定时耗材。多个条件只决定是否发送同一条消息，不生成用户可见的逐项内容。", "summary-range"], ["重复条件", "步骤 2 > 汇总条件", "同一规则内的相同对象与条件会阻止保存；不同汇总推送重复配置仅提示风险，不阻止保存。", "summary-range"]],
  rule3summary: [["投递目标", "步骤 3 > 投递目标", "App 消息中心必选；系统 notification 和 App 均只显示汇总 Title / Body。", "delivery-target"], ["每日发送", "步骤 3 > 每日发送", "按产品时区在设定时间预测当天条件。发送后保持快照，不更新、不补发、不重新计算。", "summary-delivery"], ["发布检查", "步骤 3 > 发布检查", "至少一个汇总条件、English 文案和每日发送时间必须完整。", "validation"]],
  language: [["选择语言", "统一多语言 > 选择语言", "English 始终选中。其他语言只在草稿中改变，保存后才应用。", "language-selection"], ["XLSX 导入导出", "统一多语言 > 大表操作", "工作表固定为 translations；导入只修改抽屉草稿，支持异常报告。", "xlsx-actions"], ["KV 大表", "统一多语言 > 大表", "普通推送和汇总推送都只维护 title/body；未选语言隐藏但保留值。", "product-language-matrix"], ["待补全提醒", "统一多语言 > 待补全", "已选语言缺失只提示，不阻塞保存；未选语言不校验。", "product-language-validation"]]
};
function placeAnchors(activeNotes) { $$(".note-anchor").forEach(element => element.remove()); activeNotes.forEach((note, index) => { const target = document.querySelector(`[data-anchor="${note[3]}"]`) || document.getElementById(note[3]); if (!target || target.matches("button")) return; const anchor = document.createElement("button"); anchor.className = "note-anchor"; anchor.textContent = String(index + 1); anchor.title = note[0]; anchor.onclick = () => focusNote(index); target.appendChild(anchor); }); }
function focusNote(index) { $$(".annotation-card").forEach((element, itemIndex) => element.classList.toggle("active", itemIndex === index)); $$(".anchor-highlight").forEach(element => element.classList.remove("anchor-highlight")); const active = notes[currentContext] || notes.rules, target = document.querySelector(`[data-anchor="${active[index]?.[3]}"]`) || document.getElementById(active[index]?.[3]); if (target) { target.classList.add("anchor-highlight"); target.scrollIntoView({ behavior: "smooth", block: "center" }); setTimeout(() => target.classList.remove("anchor-highlight"), 1400); } }
let currentContext = "rules";
export function renderAnnotations(context, label) { currentContext = context; const active = notes[context] || notes.rules; $("#annotationContext").textContent = label; $("#annotationList").innerHTML = active.map((note, index) => `<article class="annotation-card" data-note="${index}"><span class="annotation-number">${index + 1}</span><h3>${note[0]}</h3><div class="annotation-location">关联位置：${note[1]}</div><div class="annotation-body">${note[2]}</div></article>`).join(""); $$(".annotation-card").forEach((card, index) => card.onclick = () => focusNote(index)); requestAnimationFrame(() => placeAnchors(active)); }
