import {$,$$,esc,showToast} from "./dom.js";
import {appState,rules,events,products,fixedEnvelopeFields,fixedEnvelopeSchema,supportedLanguages} from "./state.js";
import {renderAnnotations} from "./annotations.js";
import {openRuleDrawer} from "./rule-editor.js";
import {openLanguageDrawer} from "./language-editor.js";

const workspace=$("#workspace");let query="";
const tag=(type,text)=>`<span class="el-tag el-tag--${type} is-plain">${esc(text)}</span>`;
const priorityTag=p=>tag(p==="P0"?"danger":p==="P1"?"warning":"info",p);
const statusTag=s=>tag(s==="启用"||s==="已发布"||s==="已配置"?"success":s==="草稿"||s==="停用"||s==="待配置"?"warning":s==="已撤销"?"danger":"info",s);
const activeProduct=()=>products.find(p=>p.id===appState.selectedProductId)||products[0];
const scopedRules=()=>rules.filter(r=>r.productId===appState.selectedProductId);
const scopedEvents=()=>events.filter(e=>e.productId===appState.selectedProductId);

function rulesView(){
  const source=scopedRules(),rows=source.filter(r=>!query||r.name.includes(query)||r.id.toLowerCase().includes(query.toLowerCase()));
  const enabled=source.filter(r=>r.status==="启用").length,p0=source.filter(r=>r.priority==="P0").length,stateful=source.filter(r=>r.lifecycle==="状态切换").length;
  return `<div class="filter-bar" data-anchor="filter-bar"><input class="el-input" id="keyword" placeholder="规则名称 / ID" value="${esc(query)}"><select class="el-select"><option>全部分类</option><option>安全</option><option>维护</option><option>耗材</option><option>系统</option></select><select class="el-select"><option>全部优先级</option><option>P0 紧急</option><option>P1 重要</option><option>P2 普通</option></select><select class="el-select"><option>全部状态</option><option>启用</option><option>草稿</option><option>停用</option></select><button class="el-btn el-btn--primary" data-search>查询</button><button class="el-btn" data-reset>重置</button><span class="spacer"></span><button class="el-btn" data-conflict-scan ${appState.readOnly?"disabled":""}>冲突扫描</button></div><div class="summary-strip"><span>当前产品 <strong>${esc(activeProduct().name)}</strong></span><span>启用规则 <strong>${enabled}</strong></span><span>P0 紧急 <strong>${p0}</strong></span><span>状态切换 <strong>${stateful}</strong></span><span>P0 熔断 <strong style="color:var(--el-color-danger)">${appState.fuseState.status==="closed"?"0":"1"}</strong></div><table class="el-table" data-anchor="rules-table"><thead><tr><th style="width:38px"><input type="checkbox" class="el-checkbox"></th><th>规则</th><th>分类 / 优先级</th><th>触发条件</th><th>推送消息</th><th data-anchor="language-column">多语言</th><th data-anchor="throttle-column">频控 / 生命周期</th><th>状态</th><th>更新时间</th><th class="col-ops">操作</th></tr></thead><tbody>${rows.map(r=>{const i=rules.indexOf(r);return `<tr><td><input type="checkbox" class="el-checkbox"></td><td><div class="primary-cell">${esc(r.name)}</div><div class="secondary-cell">${esc(r.id)} · ${esc(r.product)}</div></td><td>${tag("primary",r.category)} ${priorityTag(r.priority)}</td><td><div>${esc(r.trigger)}</div><div class="secondary-cell">固定信封 / 设备主体</div></td><td><div class="primary-cell">${esc(r.title)}</div><div class="secondary-cell">规则内 English + KV</div></td><td>${esc(r.languages)}</td><td><div>${esc(r.strategy)}</div><div class="secondary-cell">${esc(r.lifecycle)}</div></td><td>${statusTag(r.status)}${r.needsCompletion?'<div class="secondary-cell">待补全</div>':""}</td><td>${esc(r.updated)}</td><td class="col-ops"><button class="op-link" data-edit-rule="${i}" ${appState.readOnly?"disabled":""}>编辑</button><span class="op-divider">|</span><button class="op-link" data-language="${i}" ${appState.readOnly?"disabled":""}>多语言</button><span class="op-divider">|</span><button class="op-link" data-copy-rule="${i}" ${appState.readOnly?"disabled":""}>复制</button><span class="op-divider">|</span><button class="op-link danger" data-delete-rule="${i}" ${appState.readOnly?"disabled":""}>删除</button></td></tr>`}).join("")}</tbody></table><div class="pagination"><span>当前产品 ${rows.length} 条</span><button class="page-num active">1</button><select class="el-select" style="width:92px"><option>10 条/页</option></select></div>`;
}

function eventsView(){
  const source=scopedEvents(),rows=source.filter(e=>!query||e.name.includes(query)||e.eventType.toLowerCase().includes(query.toLowerCase()));
  return `<div class="filter-bar" data-anchor="event-filter"><input class="el-input" id="keyword" placeholder="事件名称 / eventType" value="${esc(query)}"><select class="el-select"><option>全部安全状态</option><option>已配置</option><option>待配置</option><option>已撤销</option></select><select class="el-select"><option>全部发布状态</option><option>已发布</option><option>草稿</option></select><button class="el-btn el-btn--primary" data-search>查询</button><button class="el-btn" data-reset>重置</button><span class="spacer"></span><button class="el-btn el-btn--primary" data-new-event ${appState.readOnly?"disabled":""}>新建事件</button></div><div class="help-alert" data-anchor="event-source"><strong>事件管理 · ${esc(activeProduct().name)}：</strong>事件唯一性为（productId，eventType）。固定信封只读，webhook 安全服务在规则引擎前完成认证；当前页不配置调用方授权矩阵。</div><div class="schema-box" data-anchor="fixed-envelope-summary"><div class="schema-head"><span>固定信封字段（不可修改）</span><span>deviceId 必填 · occurrenceId 按来源提供</span></div><div class="event-schema-grid compact">${fixedEnvelopeFields.map(f=>`<div><code>${esc(f.key)}</code><small>${esc(f.type)}${f.required?" · required":" · conditional"}</small></div>`).join("")}</div></div><table class="el-table" data-anchor="events-table"><thead><tr><th>事件类型</th><th>Webhook 安全</th><th>Schema</th><th>关联规则</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(e=>`<tr><td><div class="primary-cell">${esc(e.name)}</div><div class="secondary-cell">${esc(e.eventType)} · v${esc(e.schemaVersion)}</div></td><td><div class="webhook-status"><code>${esc(e.webhookEndpointId)}</code>${statusTag(e.securityStatus)}</div><div class="secondary-cell">${esc(e.webhookUrl)}</div></td><td><div>固定信封 + Payload</div><div class="secondary-cell">${e.payloadSchema.length} chars · 深度受限</div></td><td>${e.linkedRules?.length||0} 条</td><td>${statusTag(e.status)}</td><td class="col-ops"><button class="op-link" data-view-schema="${esc(e.id)}">查看 / 编辑</button><span class="op-divider">|</span><button class="op-link" data-copy-event="${esc(e.id)}" ${appState.readOnly?"disabled":""}>复制到产品</button></td></tr>`).join("")}</tbody></table><div class="pagination"><span>当前产品 ${rows.length} 条事件</span><button class="page-num active">1</button></div>`;
}

function stateView(type){if(type==="loading")return `<div class="state-box"><div class="skeleton">${Array.from({length:7},()=>'<div class="skeleton-line"></div>').join("")}</div></div>`;if(type==="error")return `<div class="state-box"><div><div class="state-icon">⚠</div><h3>消息推送数据加载失败</h3><p>网络连接异常，请重试。筛选条件已保留。</p><button class="el-btn el-btn--primary" data-retry>重新加载</button></div></div>`;if(type==="empty")return `<div class="state-box"><div><div class="state-icon">▤</div><h3>当前产品暂无${appState.tab==="rules"?"推送规则":"事件"}</h3><p>切换产品后数据按 productId 隔离；先创建当前产品的${appState.tab==="rules"?"规则":"事件"}。</p><button class="el-btn el-btn--primary" data-empty-create>${appState.tab==="rules"?"新建推送规则":"新建事件"}</button></div></div>`;return appState.tab==="rules"?rulesView():eventsView()}

function render(){
  appState.readOnly=appState.scenario==="permission";
  const selector=$("#productSelect");selector.innerHTML=products.map(p=>`<option value="${esc(p.id)}" ${p.id===appState.selectedProductId?"selected":""}>${esc(p.name)}</option>`).join("");
  workspace.innerHTML=stateView(appState.scenario);
  if(appState.scenario==="permission")workspace.insertAdjacentHTML("afterbegin",'<div class="help-alert warning" style="margin-top:0">当前账号只有查看权限：可切换产品、查看 Schema 和 webhook 状态，不可新增、编辑、复制、删除或调整发布状态。</div>');
  $("#primaryCreateBtn").textContent=appState.tab==="rules"?"新建推送规则":"新建事件";$("#primaryCreateBtn").disabled=appState.readOnly;
  $$(".business-tab").forEach(t=>t.querySelector("span").textContent=t.dataset.tab==="rules"?scopedRules().length:scopedEvents().length);
  renderAnnotations(appState.tab,appState.tab==="rules"?"推送规则列表":"事件管理");wireWorkspace();
}
function openEvents(){appState.tab="events";$(".business-tab.active")?.classList.remove("active");$("[data-tab=events]")?.classList.add("active");render()}
function seedRule(row){if(!row)return;appState.rule.id=row.id;appState.rule.productId=row.productId;appState.rule.name=row.name;appState.rule.category=row.category;appState.rule.priority=row.priority;appState.rule.reminderMode=row.lifecycle==="状态切换"?"stateSwitch":row.strategy.includes("合并")?"merge":row.strategy.includes("丢弃")?"discard":"each";const event=events.find(e=>e.productId===row.productId&&e.linkedRules?.includes(row.id));if(event)appState.rule.eventId=event.id;appState.selectedProductId=row.productId}
function openLanguage(){openLanguageDrawer({onClose:render})}
function wireWorkspace(){
  $("[data-search]")?.addEventListener("click",()=>{query=$("#keyword")?.value.trim()||"";const source=appState.tab==="rules"?scopedRules():scopedEvents();const count=source.filter(item=>!query||item.name.includes(query)||item.id.toLowerCase().includes(query.toLowerCase())).length;render();showToast(`已查询到 ${count} 条数据`)});
  $("[data-reset]")?.addEventListener("click",()=>{query="";render()});
  $("[data-retry]")?.addEventListener("click",()=>{appState.scenario="loading";$("#scenarioSelect").value="loading";render();setTimeout(()=>{appState.scenario="normal";$("#scenarioSelect").value="normal";render();showToast("数据已重新加载")},650)});
  $("[data-empty-create]")?.addEventListener("click",()=>appState.tab==="rules"?openRuleDrawer():openEventModal());
  $$('[data-edit-rule]').forEach(el=>el.addEventListener("click",()=>{seedRule(rules[Number(el.dataset.editRule)]);openRuleDrawer({edit:true})}));
  $$('[data-language]').forEach(el=>el.addEventListener("click",()=>{seedRule(rules[Number(el.dataset.language)]);openLanguage()}));
  $$('[data-copy-rule]').forEach(el=>el.addEventListener("click",()=>showToast("已复制为当前产品草稿，默认停用")));
  $$('[data-delete-rule]').forEach(el=>el.addEventListener("click",()=>openDelete(Number(el.dataset.deleteRule))));
  $("[data-conflict-scan]")?.addEventListener("click",e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="扫描中…";setTimeout(()=>{e.currentTarget.disabled=false;e.currentTarget.textContent="冲突扫描";showToast("扫描完成：发现 1 条潜在冲突","error")},700)});
  $("[data-new-event]")?.addEventListener("click",()=>openEventModal());
  $$('[data-view-schema]').forEach(el=>el.addEventListener("click",()=>openEventModal(el.dataset.viewSchema,true)));
  $$('[data-copy-event]').forEach(el=>el.addEventListener("click",()=>openCopyEventModal(el.dataset.copyEvent)));
}

function eventValidation(data){
  if(!/^[a-z0-9][a-z0-9._-]{2,119}$/.test(data.eventType))return "eventType 只能使用小写字母、数字、点、下划线或短横线（3-120 字符）";
  if(events.some(e=>e.productId===appState.selectedProductId&&e.eventType===data.eventType&&e.id!==data.id))return "当前产品已存在相同 eventType";
  if(data.payloadSchema.length>32768)return "Payload Schema 不得超过 32KB";
  let parsed;try{parsed=JSON.parse(data.payloadSchema)}catch{return "Payload Schema 不是合法 JSON"}
  if(!parsed||typeof parsed!=="object"||Array.isArray(parsed)||parsed.type!=="object")return "Payload Schema 根类型必须为 object";
  const allowedTypes=new Set(["object","array","string","number","integer","boolean","null"]);
  let schemaError="";
  const inspect=(value)=>{if(!value||typeof value!=="object"||schemaError)return;if(value.$ref&&!/^#\//.test(value.$ref)){schemaError="$ref 只能引用当前 Schema 内部路径";return}if(value.type&&(Array.isArray(value.type)?value.type.some(x=>!allowedTypes.has(x)):!allowedTypes.has(value.type))){schemaError="Schema type 不在允许类型白名单";return}Object.values(value).forEach(inspect)};
  inspect(parsed);if(schemaError)return schemaError;
  const depth=(value,d=0)=>{if(d>8)return d;if(value&&typeof value==="object")return Math.max(d,...Object.values(value).map(v=>depth(v,d+1)));return d};
  if(depth(parsed)>8)return "Payload Schema 深度不得超过 8 层";return "";
}

function openEventModal(id,readOnly=false){
  const existing=id?events.find(e=>e.id===id):null;
  const event=existing||{id:"",eventType:"custom.device.notice",schemaVersion:"1.0",name:"新自定义事件",productId:appState.selectedProductId,product:activeProduct().name,status:"草稿",webhookEndpointId:`wh-${appState.selectedProductId}-draft`,webhookUrl:`https://hooks.example.test/e/wh-${appState.selectedProductId}-draft`,securityStatus:"待配置",securityConfigVersion:"—",payloadSchema:'{\n  "type": "object",\n  "properties": {},\n  "additionalProperties": false\n}',linkedRules:[],updated:"—"};
  const modal=document.createElement("div");modal.className="modal-host";
  const securityActions=readOnly?"":`<div class="webhook-actions"><button class="el-btn el-btn--small" data-webhook-config>配置安全策略</button><button class="el-btn el-btn--small" data-webhook-rotate>轮换</button><button class="el-btn el-btn--small el-btn--danger" data-webhook-revoke>撤销</button></div>`;
  modal.innerHTML=`<div class="modal modal-wide"><header class="modal-header"><h3>${readOnly?"事件详情":existing?"编辑事件":"新建事件"}</h3><button class="icon-btn" data-modal-close>×</button></header><div class="modal-body"><div class="help-alert">事件按产品独立定义，唯一性为（${esc(appState.selectedProductId)}，eventType）。固定信封只读；webhook 安全服务在规则引擎前完成认证，旧 Event Token 不再使用。</div><div class="form-grid"><label class="form-row"><span class="form-label">eventType</span><input class="el-input" data-event-field="eventType" value="${esc(event.eventType)}" ${readOnly?"disabled":""}></label><label class="form-row"><span class="form-label">schemaVersion</span><input class="el-input" data-event-field="schemaVersion" value="${esc(event.schemaVersion)}" ${readOnly?"disabled":""}></label><label class="form-row"><span class="form-label">事件名称</span><input class="el-input" data-event-field="name" value="${esc(event.name)}" ${readOnly?"disabled":""}></label><label class="form-row"><span class="form-label">发布状态</span><select class="el-select" data-event-field="status" ${readOnly?"disabled":""}><option ${event.status==="草稿"?"selected":""}>草稿</option><option ${event.status==="已发布"?"selected":""}>已发布</option></select></label></div><div class="webhook-box" data-anchor="webhook-security"><div><strong>Webhook 安全入口</strong><span>第三方使用链接与安全配置发送事件</span></div><div class="webhook-detail"><code>${esc(event.webhookEndpointId)}</code><span>${esc(event.webhookUrl)}</span><span>${statusTag(event.securityStatus)} · 配置版本 ${esc(event.securityConfigVersion)}</span></div>${securityActions}<small>URL secret query 与凭证脱敏；完整凭证仅创建/轮换结果展示且不得进入日志。</small></div><div class="form-row full" data-anchor="fixed-envelope"><span class="form-label">固定信封（只读）</span><div class="schema-box"><pre>${esc(fixedEnvelopeSchema)}</pre></div></div><label class="form-row full" data-anchor="payload-schema"><span class="form-label">自定义 Payload JSON Schema</span><textarea class="el-textarea schema-editor" data-event-field="payloadSchema" ${readOnly?"disabled":""}>${esc(event.payloadSchema)}</textarea><p class="form-help">限制：JSON Schema 深度 ≤ 8、≤ 32KB、类型白名单、$ref 仅允许当前文档内部引用。</p></label>${existing?`<div class="form-row full"><span class="form-label">直接关联规则</span><div class="chip-list">${(event.linkedRules||[]).map(r=>`<span class="chip">${esc(r)}</span>`).join("")||"—"}</div></div>`:""}</div><footer class="modal-footer"><button class="el-btn" data-modal-close>关闭</button>${readOnly?"":'<button class="el-btn el-btn--primary" data-save-event>保存为草稿</button><button class="el-btn el-btn--primary" data-publish-event>发布事件</button>'}</footer></div>`;
  document.body.appendChild(modal);modal.querySelectorAll("[data-modal-close]").forEach(x=>x.onclick=()=>modal.remove());
  if(readOnly)return;
  modal.querySelectorAll("[data-event-field]").forEach(el=>{const update=()=>{event[el.dataset.eventField]=el.value};el.addEventListener("input",update);el.addEventListener("change",update)});
  const refreshWebhook=()=>{const detail=modal.querySelector(".webhook-detail");if(!detail)return;detail.innerHTML=`<code>${esc(event.webhookEndpointId)}</code><span>${esc(event.webhookUrl)}</span><span>${statusTag(event.securityStatus)} · 配置版本 ${esc(event.securityConfigVersion)}</span>`};
  modal.querySelector("[data-webhook-config]")?.addEventListener("click",()=>{event.securityStatus="已配置";event.securityConfigVersion=event.securityConfigVersion==="—"?"v1":event.securityConfigVersion;refreshWebhook();showToast("安全配置已验证")});
  modal.querySelector("[data-webhook-rotate]")?.addEventListener("click",()=>{event.securityStatus="已配置";event.securityConfigVersion=`v${Number(String(event.securityConfigVersion).replace("v","")||0)+1}`;refreshWebhook();showToast(`安全配置已轮换至 ${event.securityConfigVersion}`)});
  modal.querySelector("[data-webhook-revoke]")?.addEventListener("click",()=>{event.securityStatus="已撤销";refreshWebhook();showToast("Webhook 已撤销，事件触发将 fail-closed","error")});
  modal.querySelector("[data-save-event]").addEventListener("click",()=>saveEvent(event,"草稿"));modal.querySelector("[data-publish-event]").addEventListener("click",()=>saveEvent(event,"已发布"));
  function saveEvent(data,status){data.status=status;data.productId=appState.selectedProductId;data.product=activeProduct().name;data.id=data.id||`${data.eventType}.draft.${data.productId}`;const error=eventValidation(data);if(error){showToast(error,"error");return}if(status==="已发布"&&data.securityStatus!=="已配置"){showToast("请先配置并验证 webhook 安全策略","error");return}if(existing)Object.assign(existing,data);else events.push({...data,updated:"2026-08-03 15:30"});modal.remove();render();showToast(status==="已发布"?"事件已发布，可供当前产品规则选择":"事件草稿已保存")}
}

function openCopyEventModal(id){
  const source=events.find(e=>e.id===id);if(!source)return;const targets=products.filter(p=>p.id!==source.productId);const modal=document.createElement("div");modal.className="modal-host";modal.innerHTML=`<div class="modal"><header class="modal-header"><h3>复制事件到其他产品</h3><button class="icon-btn" data-modal-close>×</button></header><div class="modal-body"><div class="help-alert">复制 Payload Schema 与直接关联规则；目标事件为草稿，webhook 安全配置不复制原始凭证，目标规则默认停用。</div><div class="check-row" data-anchor="copy-targets">${targets.map(p=>`<label><input type="checkbox" data-copy-target="${esc(p.id)}"> ${esc(p.name)}</label>`).join("")}</div><div class="copy-report" data-copy-report><span>尚未执行</span></div></div><footer class="modal-footer"><button class="el-btn" data-modal-close>取消</button><button class="el-btn el-btn--primary" data-run-copy>开始复制</button></footer></div>`;document.body.appendChild(modal);modal.querySelectorAll("[data-modal-close]").forEach(x=>x.onclick=()=>modal.remove());modal.querySelector("[data-run-copy]").addEventListener("click",()=>{const targetIds=[...modal.querySelectorAll("[data-copy-target]:checked")].map(x=>x.dataset.copyTarget);if(!targetIds.length){showToast("请选择目标产品","error");return}const report=copyEvent(source,targetIds);modal.querySelector("[data-copy-report]").innerHTML=`<strong>复制结果</strong>${report.map(x=>`<div class="copy-result ${x.ok?"ok":"skip"}">${x.ok?"✓":"↷"} ${esc(x.product)}：${esc(x.message)}</div>`).join("")}`;showToast("复制完成，安全配置待目标产品重新配置")})
}
function copyEvent(source,targetIds){const report=[];targetIds.forEach(targetId=>{const p=products.find(x=>x.id===targetId),duplicate=events.find(e=>e.productId===targetId&&e.eventType===source.eventType);if(duplicate){report.push({product:p.name,ok:false,message:`跳过：已存在 ${source.eventType}`});return}const copyId=`${source.eventType}.draft.${targetId}`,copy={...source,id:copyId,productId:targetId,product:p.name,status:"草稿",webhookEndpointId:`wh-${targetId}-${source.eventType.replace(/[^a-z0-9]+/gi,"-")}`,webhookUrl:`https://hooks.example.test/e/wh-${targetId}`,securityStatus:"待配置",securityConfigVersion:"—",linkedRules:[],copiedFrom:source.id,updated:"2026-08-03 15:30"};events.push(copy);let ruleCount=0;(source.linkedRules||[]).forEach(ruleId=>{const origin=rules.find(r=>r.id===ruleId);if(!origin)return;const newRule={...origin,id:`${origin.id}-${targetId}-copy`,productId:targetId,product:p.name,status:"停用",updated:"2026-08-03 15:30",needsCompletion:true,eventId:copyId};rules.push(newRule);copy.linkedRules.push(newRule.id);ruleCount++});report.push({product:p.name,ok:true,message:`事件草稿已创建；${ruleCount} 条关联规则已停用，webhook 安全需重新配置`})});render();return report}

function openDelete(index){const r=rules[index]||rules[0],modal=document.createElement("div");modal.className="modal-host";modal.innerHTML=`<div class="modal"><header class="modal-header"><h3>删除推送规则</h3><button class="icon-btn" data-modal-close>×</button></header><div class="modal-body"><p>确定删除「<strong>${esc(r.name)}</strong>」吗？</p><div class="help-alert danger">删除后数据不可恢复；活跃设备实例会按安全上限结束。</div></div><footer class="modal-footer"><button class="el-btn" data-modal-close>取消</button><button class="el-btn el-btn--danger" data-confirm-delete>删除</button></footer></div>`;document.body.appendChild(modal);modal.querySelectorAll("[data-modal-close]").forEach(x=>x.onclick=()=>modal.remove());modal.querySelector("[data-confirm-delete]").onclick=()=>{modal.remove();showToast("规则已删除")}}

$$('.business-tab').forEach(tab=>tab.addEventListener("click",()=>{appState.tab=tab.dataset.tab;query="";$$('.business-tab').forEach(x=>x.classList.toggle("active",x===tab));render()}));
$("#productSelect").addEventListener("change",e=>{appState.selectedProductId=e.target.value;appState.rule.productId=e.target.value;const first=scopedEvents()[0];if(first)appState.rule.eventId=first.id;query="";render();showToast(`已切换至 ${activeProduct().name}，规则、事件、占位符和跳转页面已刷新`)});
$("#scenarioSelect").addEventListener("change",e=>{appState.scenario=e.target.value;render()});
$("#refreshBtn").addEventListener("click",e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="刷新中…";setTimeout(()=>{e.currentTarget.disabled=false;e.currentTarget.textContent="刷新";render();showToast("已刷新")},500)});
$("#primaryCreateBtn").addEventListener("click",()=>appState.tab==="rules"?openRuleDrawer():openEventModal());
$("#annotationToggle").addEventListener("click",()=>$(".prototype-shell").classList.add("annotation-closed"));$("#annotationReopen").addEventListener("click",()=>$(".prototype-shell").classList.remove("annotation-closed"));document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#overlayRoot").replaceChildren()});render();
const demo=new URLSearchParams(location.search).get("demo");if(demo==="language")openLanguageDrawer({onClose:render});if(demo==="events")openEvents();if(demo==="cloud-cycle"){appState.rule.triggerType="cloud";openRuleDrawer({edit:true});setTimeout(()=>$("#ruleDrawer [data-step=\"1\"]")?.click(),0)}if(/^rule[1-3]$/.test(demo||"")){openRuleDrawer({edit:true});const step=Number(demo.slice(-1));if(step>1)setTimeout(()=>$("#ruleDrawer [data-step=\""+step+"\"]")?.click(),0)}
