import {$,$$,esc,showToast} from "./dom.js";
import {appState,rules,events} from "./state.js";
import {renderAnnotations} from "./annotations.js";
import {openRuleDrawer} from "./rule-editor.js";
import {openLanguageDrawer} from "./language-editor.js";

const workspace=$("#workspace");let query="";
const tag=(type,text)=>`<span class="el-tag el-tag--${type} is-plain">${text}</span>`;
const priorityTag=p=>tag(p==="P0"?"danger":p==="P1"?"warning":"info",p);
const statusTag=s=>tag(s==="启用"||s==="已授权"?"success":s==="草稿"?"warning":"info",s);

function rulesView(){const rows=rules.filter(r=>!query||r.name.includes(query)||r.id.toLowerCase().includes(query.toLowerCase()));return `<div class="filter-bar" data-anchor="filter-bar"><input class="el-input" id="keyword" placeholder="规则名称 / ID" value="${esc(query)}"><select class="el-select"><option>全部分类</option><option>安全</option><option>维护</option><option>耗材</option></select><select class="el-select"><option>全部优先级</option><option>P0 紧急</option><option>P1 重要</option><option>P2 常规</option></select><select class="el-select"><option>全部状态</option><option>启用</option><option>草稿</option><option>停用</option></select><button class="el-btn el-btn--primary" data-search>查询</button><button class="el-btn" data-reset>重置</button><span class="spacer"></span><button class="el-btn" data-conflict-scan ${appState.readOnly?"disabled":""}>冲突扫描</button></div><div class="summary-strip"><span>启用规则 <strong>9</strong></span><span>P0 紧急 <strong>2</strong></span><span>连续提醒 <strong>3</strong></span><span>今日触发 <strong>1,284</strong></span><span>熔断 <strong style="color:var(--el-color-danger)">1</strong></span></div><table class="el-table" data-anchor="rules-table"><thead><tr><th style="width:38px"><input type="checkbox" class="el-checkbox"></th><th>规则</th><th>分类/优先级</th><th>触发条件</th><th>推送消息</th><th data-anchor="language-column">多语言</th><th>市场</th><th data-anchor="throttle-column">节流/生命周期</th><th>状态</th><th>更新时间</th><th class="col-ops">操作</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><input type="checkbox" class="el-checkbox"></td><td><div class="primary-cell">${r.name}</div><div class="secondary-cell">${r.id} · ${r.product}</div></td><td>${tag("primary",r.category)} ${priorityTag(r.priority)}</td><td><div>${r.trigger}</div><div class="secondary-cell">设备/事件载荷解析</div></td><td><div class="primary-cell">${r.title}</div><div class="secondary-cell">规则内消息内容</div></td><td>${r.languages}</td><td>${r.regions}</td><td><div>${r.throttle}</div><div class="secondary-cell">${r.lifecycle}</div></td><td>${statusTag(r.status)}</td><td>${r.updated}</td><td class="col-ops"><button class="op-link" data-edit-rule="${i}" ${appState.readOnly?"disabled":""}>编辑</button><span class="op-divider">|</span><button class="op-link" data-language="${i}" ${appState.readOnly?"disabled":""}>多语言</button><span class="op-divider">|</span><button class="op-link" data-copy-rule="${i}" ${appState.readOnly?"disabled":""}>复制</button><span class="op-divider">|</span><button class="op-link danger" data-delete-rule="${i}" ${appState.readOnly?"disabled":""}>删除</button></td></tr>`).join("")}</tbody></table><div class="pagination"><span>共 12 条</span><button class="page-num active">1</button><button class="page-num">2</button><select class="el-select" style="width:92px"><option>10 条/页</option></select></div>`}

function eventsView(){const rows=events.filter(e=>!query||e.name.includes(query)||e.id.includes(query));return `<div class="filter-bar" data-anchor="event-filter"><input class="el-input" id="keyword" placeholder="事件名称 / event_type" value="${esc(query)}"><select class="el-select"><option>全部来源</option><option>设备云</option><option>固件服务</option></select><select class="el-select"><option>全部授权状态</option><option>已授权</option><option>待授权</option></select><button class="el-btn el-btn--primary" data-search>查询</button><button class="el-btn" data-reset>重置</button><span class="spacer"></span><button class="el-btn" data-new-event ${appState.readOnly?"disabled":""}>注册事件</button></div><div class="help-alert" data-anchor="event-source"><strong>授权事件来源：</strong>在本页注册事件 Schema 并授权至当前产品后，才会出现在推送规则的「事件触发」选择器中。调用方只可触发已授权的 caller_id × event_type × productId 组合。</div><table class="el-table" data-anchor="events-table"><thead><tr><th>事件</th><th>调用方 / 来源</th><th>Schema 受众字段</th><th>产品授权</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map((e,i)=>`<tr><td><div class="primary-cell">${e.name}</div><div class="secondary-cell">${e.id}</div></td><td>${e.caller}<div class="secondary-cell">${e.source}</div></td><td><div>deviceId（按需）</div><div class="secondary-cell">userIds?: string[]</div></td><td>${e.scope}</td><td>${statusTag(e.status)}</td><td class="col-ops"><button class="op-link" data-view-schema="${i}">查看 Schema</button><span class="op-divider">|</span><button class="op-link" data-edit-event="${i}" ${appState.readOnly?"disabled":""}>授权配置</button></td></tr>`).join("")}</tbody></table><div class="pagination"><span>共 3 条</span><button class="page-num active">1</button></div>`}

function stateView(type){if(type==="loading")return `<div class="state-box"><div class="skeleton">${Array.from({length:7},()=>'<div class="skeleton-line"></div>').join("")}</div></div>`;if(type==="error")return `<div class="state-box"><div><div class="state-icon">⚠</div><h3>消息推送数据加载失败</h3><p>网络连接异常，请重试。筛选条件已保留。</p><button class="el-btn el-btn--primary" data-retry>重新加载</button></div></div>`;if(type==="empty")return `<div class="state-box"><div><div class="state-icon">▤</div><h3>${appState.tab==="rules"?"暂无推送规则":"暂无授权事件"}</h3><p>${appState.tab==="rules"?"先创建第一条推送规则，并在规则内录入消息内容。":"先注册事件、发布 Schema 并授权至当前产品。"}</p><button class="el-btn el-btn--primary" data-empty-create>${appState.tab==="rules"?"新建推送规则":"注册事件"}</button></div></div>`;return appState.tab==="rules"?rulesView():eventsView()}

function render(){appState.readOnly=appState.scenario==="permission";workspace.innerHTML=stateView(appState.scenario);if(appState.scenario==="permission")workspace.insertAdjacentHTML("afterbegin",'<div class="help-alert warning" style="margin-top:0">当前账号只有查看权限：可筛选、查看 Schema 和预览，不可新增、编辑、复制、删除或调整授权。</div>');$("#primaryCreateBtn").textContent=appState.tab==="rules"?"新建推送规则":"注册事件";$("#primaryCreateBtn").disabled=appState.readOnly;renderAnnotations(appState.tab,appState.tab==="rules"?"推送规则列表":"授权事件");wireWorkspace()}
function openEvents(){appState.tab="events";$$(".business-tab").forEach(x=>x.classList.toggle("active",x.dataset.tab==="events"));render()}
function openLanguage(){openLanguageDrawer({onClose:render})}
function wireWorkspace(){
  $("[data-search]")?.addEventListener("click",()=>{query=$("#keyword")?.value.trim()||"";const list=appState.tab==="rules"?rules:events;const count=list.filter(item=>!query||item.name.includes(query)||item.id.toLowerCase().includes(query.toLowerCase())).length;render();showToast(`已查询到 ${count} 条数据`)});
  $("[data-reset]")?.addEventListener("click",()=>{query="";render()});$("[data-retry]")?.addEventListener("click",()=>{appState.scenario="loading";$("#scenarioSelect").value="loading";render();setTimeout(()=>{appState.scenario="normal";$("#scenarioSelect").value="normal";render();showToast("数据已重新加载")},650)});
  $("[data-empty-create]")?.addEventListener("click",()=>appState.tab==="rules"?openRuleDrawer({onOpenEvents:openEvents}):openEventModal());$$('[data-edit-rule]').forEach(el=>el.addEventListener("click",()=>openRuleDrawer({edit:true,onOpenEvents:openEvents})));$$('[data-language]').forEach(el=>el.addEventListener("click",openLanguage));$$('[data-copy-rule]').forEach(el=>el.addEventListener("click",()=>showToast("已复制为草稿：设备溢奶紧急提醒（副本）")));$$('[data-delete-rule]').forEach(el=>el.addEventListener("click",()=>openDelete(Number(el.dataset.deleteRule))));$("[data-conflict-scan]")?.addEventListener("click",e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="扫描中…";setTimeout(()=>{e.currentTarget.disabled=false;e.currentTarget.textContent="冲突扫描";showToast("扫描完成：发现 1 条潜在冲突","error")},700)});$("[data-new-event]")?.addEventListener("click",openEventModal);$$('[data-view-schema]').forEach(el=>el.addEventListener("click",()=>openEventModal(Number(el.dataset.viewSchema),true)));$$('[data-edit-event]').forEach(el=>el.addEventListener("click",()=>openEventModal(Number(el.dataset.editEvent))));
}
function openEventModal(index=0,readOnly=false){const event=events[index]||events[0];const modal=document.createElement("div");modal.className="modal-host";modal.innerHTML=`<div class="modal"><header class="modal-header"><h3>${readOnly?"事件 Schema":"注册 / 授权事件"}</h3><button class="icon-btn" data-modal-close>×</button></header><div class="modal-body"><div class="form-row"><label>event_type</label><input class="el-input" value="${esc(event.id)}" ${readOnly?"disabled":""}></div><div class="form-row"><label>调用方</label><div class="readonly-field">${event.caller} · ${event.source}</div></div><div class="form-row"><label>Schema</label><pre class="schema-box" style="padding:12px">${esc(event.schema)}</pre><p class="form-help">userIds 为可选数组：有值作为候选用户；无值时按产品绑定用户解析。设备类事件还须提供 deviceId。</p></div><div class="form-row"><label>授权范围</label><div class="readonly-field">${event.caller} × ${event.id} × S12 Pro</div></div></div><footer class="modal-footer"><button class="el-btn" data-modal-close>关闭</button>${readOnly?"":'<button class="el-btn el-btn--primary" data-save-event>保存并授权</button>'}</footer></div>`;document.body.appendChild(modal);$$('[data-modal-close]',modal).forEach(x=>x.onclick=()=>modal.remove());$('[data-save-event]',modal)?.addEventListener("click",e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="保存中…";setTimeout(()=>{modal.remove();showToast("事件已发布并授权至当前产品")},550)})}
function openDelete(index){const r=rules[index]||rules[0];const modal=document.createElement("div");modal.className="modal-host";modal.innerHTML=`<div class="modal"><header class="modal-header"><h3>删除推送规则</h3><button class="icon-btn" data-modal-close>×</button></header><div class="modal-body"><p>确定删除「<strong>${r.name}</strong>」吗？</p><div class="help-alert danger">删除后数据不可恢复。若规则处于连续提醒中，已激活实例将按安全上限结束。</div></div><footer class="modal-footer"><button class="el-btn" data-modal-close>取消</button><button class="el-btn el-btn--danger" data-confirm-delete>删除</button></footer></div>`;document.body.appendChild(modal);$$('[data-modal-close]',modal).forEach(x=>x.onclick=()=>modal.remove());$('[data-confirm-delete]',modal).onclick=e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="删除中…";setTimeout(()=>{modal.remove();showToast("规则已删除")},600)}}

$$(".business-tab").forEach(tab=>tab.addEventListener("click",()=>{appState.tab=tab.dataset.tab;query="";$$(".business-tab").forEach(x=>x.classList.toggle("active",x===tab));render()}));$("#scenarioSelect").addEventListener("change",e=>{appState.scenario=e.target.value;render()});$("#refreshBtn").addEventListener("click",e=>{e.currentTarget.disabled=true;e.currentTarget.textContent="刷新中…";setTimeout(()=>{e.currentTarget.disabled=false;e.currentTarget.textContent="刷新";showToast("已刷新")},500)});$("#primaryCreateBtn").addEventListener("click",()=>appState.tab==="rules"?openRuleDrawer({onOpenEvents:openEvents}):openEventModal());$("#annotationToggle").addEventListener("click",()=>$(".prototype-shell").classList.add("annotation-closed"));$("#annotationReopen").addEventListener("click",()=>$(".prototype-shell").classList.remove("annotation-closed"));document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#overlayRoot").replaceChildren()});render();
const demo=new URLSearchParams(location.search).get("demo");if(demo==="language")openLanguage();if(demo==="events")openEvents();if(/^rule[1-4]$/.test(demo||"")){openRuleDrawer({edit:true,onOpenEvents:openEvents});const step=Number(demo.slice(-1));if(step>1)document.querySelector(`[data-step="${step}"]`)?.click()}
