import {$,$$,esc,showToast} from "./dom.js";
import {appState,emptyLanguageValues,products,rules,newRule} from "./state.js";
import {renderAnnotations} from "./annotations.js";
import {openRuleDrawer,resetRuleDraft} from "./rule-editor.js";
import {openProductLanguageDrawer,openRuleLanguageDrawer} from "./language-editor.js";
import {openProductPicker,renderProductPickerTrigger} from "./product-picker.js";

const workspace=$("#workspace");let query="",statusQuery="",categoryQuery="";
const activeProduct=()=>products.find(item=>item.id===appState.selectedProductId)||products[0];
const scopedRules=()=>rules.filter(item=>item.productId===appState.selectedProductId);
const statusTag=status=>`<span class="el-tag el-tag--${status==="启用"?"success":status==="草稿"?"warning":"info"} is-plain">${esc(status)}</span>`;
function futureScope(){return `<div class="future-scope" data-anchor="future-scope"><strong>后续版本能力</strong><span>事件管理、Webhook 接入、状态切换、优先级、跨产品复制和自定义深链不在当前页面提供入口。</span></div>`}
function rulesView(){const source=scopedRules(),rows=source.filter(item=>(!query||item.name.includes(query)||item.id.toLowerCase().includes(query.toLowerCase()))&&(!statusQuery||item.status===statusQuery)&&(!categoryQuery||item.category===categoryQuery)),enabled=source.filter(item=>item.status==="启用").length;return `<div class="help-alert" data-anchor="p0-scope"><strong>消息推送：</strong>使用当前产品已有的设备、云计时器和耗材来源。提醒只发给对应设备已绑定的用户。</div><div class="filter-bar" data-anchor="filter-bar"><input class="el-input" id="keyword" placeholder="规则名称 / ID" value="${esc(query)}"><select class="el-select" id="categoryFilter"><option value="">全部分类</option><option value="耗材通知" ${categoryQuery==="耗材通知"?"selected":""}>耗材通知</option><option value="事件通知" ${categoryQuery==="事件通知"?"selected":""}>事件通知</option></select><select class="el-select" id="statusFilter"><option value="">全部状态</option><option value="启用" ${statusQuery==="启用"?"selected":""}>启用</option><option value="草稿" ${statusQuery==="草稿"?"selected":""}>草稿</option></select><button class="el-btn el-btn--primary" data-search>查询</button><button class="el-btn" data-reset>重置</button></div><div class="summary-strip"><span>当前产品 <strong>${esc(activeProduct().name)}</strong></span><span>启用规则 <strong>${enabled}</strong></span><span>消息分类 <strong>耗材通知 / 事件通知</strong></span><span>投递目标 <strong>消息中心 / 系统通知</strong></span></div><table class="el-table" data-anchor="rules-table"><thead><tr><th style="width:38px"><input type="checkbox" class="el-checkbox"></th><th>规则</th><th>触发条件</th><th>推送消息</th><th data-anchor="language-column">多语言</th><th>投递方式</th><th>状态</th><th>更新时间</th><th class="col-ops">操作</th></tr></thead><tbody>${rows.map(item=>{const index=rules.indexOf(item);return `<tr><td><input type="checkbox" class="el-checkbox"></td><td><div class="primary-cell">${esc(item.name)}</div><div class="secondary-cell">${esc(item.id)} · ${esc(item.category)}</div></td><td>${esc(item.trigger)}</td><td><div class="primary-cell">${esc(item.title)}</div><div class="secondary-cell">可单独编辑多语言</div></td><td>${esc(item.languages)} 个语言</td><td>${esc(item.strategy)}</td><td>${statusTag(item.status)}</td><td>${esc(item.updated)}</td><td class="col-ops"><button class="op-link" data-edit-rule="${index}" ${appState.readOnly?"disabled":""}>编辑</button><span class="op-divider">|</span><button class="op-link" data-rule-language="${index}" data-anchor="rule-language-entry" ${appState.readOnly?"disabled":""}>多语言</button><span class="op-divider">|</span><button class="op-link danger" data-delete-rule="${index}" ${appState.readOnly?"disabled":""}>删除</button></td></tr>`}).join("")}</tbody></table><div class="pagination"><span>当前产品 ${rows.length} 条</span><button class="page-num active">1</button></div>${futureScope()}`}
function stateView(){if(appState.scenario==="loading")return `<div class="state-box"><div class="skeleton">${Array.from({length:6},()=>'<div class="skeleton-line"></div>').join("")}</div></div>`;if(appState.scenario==="error")return `<div class="state-box"><div><div class="state-icon">⚠</div><h3>推送规则加载失败</h3><p>网络连接异常，筛选条件已保留。</p><button class="el-btn el-btn--primary" data-retry>重新加载</button></div></div>`;if(appState.scenario==="empty")return `<div class="state-box"><div><div class="state-icon">▤</div><h3>当前产品暂无推送规则</h3><p>可以直接为设备、云计时器或耗材来源创建第一条规则。</p><button class="el-btn el-btn--primary" data-empty-create>新建推送规则</button></div></div>`;return rulesView()}
function render(){appState.readOnly=appState.scenario==="permission";renderProductPickerTrigger();$("#annotationScenarioSelect").value=appState.scenario;workspace.innerHTML=stateView();if(appState.readOnly)workspace.insertAdjacentHTML("afterbegin",'<div class="help-alert warning">当前账号只有查看权限：可切换产品和查看规则，不能新增、编辑或修改多语言。</div>');$("#primaryCreateBtn").textContent="新建推送规则";$("#primaryCreateBtn").disabled=appState.readOnly;$("#productLanguageBtn").disabled=appState.readOnly;$("#ruleCount").textContent=String(scopedRules().length);renderAnnotations("rules","推送规则列表");wireWorkspace()}
function seedRule(row){appState.selectedProductId=row.productId;appState.rule={...newRule(),...row,productId:row.productId,presetLinkId:row.presetLinkId||"message-center"};const values=emptyLanguageValues();values["en-US"]={title:row.title,body:"Your device needs attention."};appState.message.values=values;appState.activeContentField="title"}
function openNew(){resetRuleDraft();openRuleDrawer()}
function openDelete(index){const row=rules[index];if(!row)return;const modal=document.createElement("div");modal.className="modal-host";modal.innerHTML=`<div class="modal"><header class="modal-header"><h3>删除推送规则</h3><button class="icon-btn" data-close>×</button></header><div class="modal-body">确定删除「${esc(row.name)}」吗？删除后不能恢复。</div><footer class="modal-footer"><button class="el-btn" data-close>取消</button><button class="el-btn el-btn--danger" data-confirm>删除</button></footer></div>`;document.body.appendChild(modal);modal.querySelectorAll("[data-close]").forEach(item=>item.onclick=()=>modal.remove());modal.querySelector("[data-confirm]").onclick=()=>{rules.splice(index,1);modal.remove();render();showToast("规则已删除")}}
function openLanguages(){openProductLanguageDrawer({onClose:render})}
function setProduct(id){if(!products.some(product=>product.id===id))return;appState.selectedProductId=id;query="";statusQuery="";categoryQuery="";render()}
function wireWorkspace(){$("[data-search]")?.addEventListener("click",()=>{query=$("#keyword")?.value.trim()||"";statusQuery=$("#statusFilter")?.value||"";categoryQuery=$("#categoryFilter")?.value||"";render();const count=scopedRules().filter(item=>(!query||item.name.includes(query)||item.id.toLowerCase().includes(query.toLowerCase()))&&(!statusQuery||item.status===statusQuery)&&(!categoryQuery||item.category===categoryQuery)).length;showToast(`已查询到 ${count} 条规则`)});$("[data-reset]")?.addEventListener("click",()=>{query="";statusQuery="";categoryQuery="";render()});$("[data-retry]")?.addEventListener("click",()=>{appState.scenario="loading";render();setTimeout(()=>{appState.scenario="normal";render();showToast("数据已重新加载")},500)});$("[data-empty-create]")?.addEventListener("click",openNew);$$('[data-edit-rule]').forEach(item=>item.addEventListener("click",()=>{seedRule(rules[Number(item.dataset.editRule)]);openRuleDrawer({edit:true})}));$$('[data-rule-language]').forEach(item=>item.addEventListener("click",()=>openRuleLanguageDrawer(rules[Number(item.dataset.ruleLanguage)],{onClose:render})));$$('[data-delete-rule]').forEach(item=>item.addEventListener("click",()=>openDelete(Number(item.dataset.deleteRule))))}
$("#productPickerTrigger").addEventListener("click",openProductPicker);$("#annotationScenarioSelect").addEventListener("change",event=>{appState.scenario=event.target.value;render()});$("#refreshBtn").addEventListener("click",()=>{appState.scenario="loading";render();setTimeout(()=>{appState.scenario="normal";render();showToast("规则已刷新")},450)});$("#primaryCreateBtn").addEventListener("click",openNew);$("#productLanguageBtn").addEventListener("click",openLanguages);$("#annotationToggle").addEventListener("click",()=>{$(".prototype-shell").classList.add("annotation-closed")});$("#annotationReopen").addEventListener("click",()=>{$(".prototype-shell").classList.remove("annotation-closed")});window.addEventListener("message-push:rule-changed",render);window.addEventListener("message-push:product-changed",event=>setProduct(event.detail));render();

const demo=new URLSearchParams(location.search).get("demo");if(demo==="language")setTimeout(openLanguages,0);if(demo==="cloud"){appState.rule.triggerType="cloud";openRuleDrawer({edit:true})}
