import {$,$$,esc,showToast} from "./dom.js";
import {appState,supportedLanguages,placeholders} from "./state.js";
import {renderAnnotations} from "./annotations.js";

const tokens=value=>[...new Set((value||"").match(/\$\{[^}]+\}/g)||[])];
function selectedMissing(){return appState.selectedLocales.filter(code=>{const v=appState.message.values[code]||{};return !v.title?.trim()||!v.body?.trim()})}
function selectedTokenErrors(){const unknown=[];const unsupported=[];appState.selectedLocales.forEach(code=>{const v=appState.message.values[code]||{};tokens(`${v.title} ${v.body}`).forEach(t=>{if(!placeholders.some(p=>p.token===t))unknown.push(`${code}: ${t}`);else if(!placeholders.find(p=>p.token===t).supported.includes(appState.rule.triggerType))unsupported.push(`${code}: ${t}`)})});return {unknown:[...new Set(unknown)],unsupported:[...new Set(unsupported)]}}
function completion(){const filled=appState.selectedLocales.filter(code=>{const v=appState.message.values[code]||{};return v.title?.trim()&&v.body?.trim()}).length;return `${filled}/${appState.selectedLocales.length}`}
function bodyMarkup(){const missing=selectedMissing();const errors=selectedTokenErrors();return `<div class="help-alert" data-anchor="language-scope"><strong>规则内多语言 KV。</strong> English 始终勾选且不可取消，是默认语言和 fallback；中文默认勾选但可取消。取消语言保留草稿，不参与发布校验。</div><div class="form-section" data-anchor="language-selector"><div class="section-title"><h3>发布语言（18 语言目录）</h3><p>已选 ${appState.selectedLocales.length} / 18 · 完成度 ${completion()}</p></div><div class="locale-grid">${supportedLanguages.map(([code,name])=>{const checked=appState.selectedLocales.includes(code);return `<label class="locale-option ${checked?"selected":""}"><input type="checkbox" data-locale-toggle="${code}" ${checked?"checked":""} ${code==="en-US"?"disabled":""}><span><strong>${name}</strong><small>${code}${code==="en-US"?" · 默认 fallback":""}</small></span></label>`}).join("")}</div></div><div class="form-section" data-anchor="lang-matrix"><div class="section-title"><h3>title / body KV 矩阵</h3><p>仅已选语言参与发布校验；未选行仍可编辑草稿</p></div><div class="matrix-wrap"><table class="lang-matrix"><thead><tr><th style="width:150px">语言 / 发布</th><th>Title</th><th>Body</th></tr></thead><tbody>${supportedLanguages.map(([code,name])=>{const v=appState.message.values[code]||{title:"",body:""};const checked=appState.selectedLocales.includes(code);return `<tr class="${checked?"":"is-deselected"}"><td><strong>${name}</strong><div class="secondary-cell">${code} · ${checked?"参与发布":"仅保留草稿"}</div></td><td><textarea data-lang="${code}" data-key="title" placeholder="请输入标题">${esc(v.title)}</textarea></td><td><textarea data-lang="${code}" data-key="body" placeholder="请输入正文">${esc(v.body)}</textarea></td></tr>`}).join("")}</tbody></table></div></div><div class="form-section" data-anchor="message-link"><div class="section-title"><h3>跳转页面</h3><p>在规则步骤 1 统一配置</p></div><div class="readonly-field">${esc(appState.message.cozyLinkMode==="none"?"不跳转":appState.message.cozyLinkMode==="preset"?`产品预设 · ${appState.message.cozyLink}`:appState.message.cozyLink)}</div><p class="form-help">支持模式：不跳转、当前产品预设页面、自定义 cozy:// 深链。自定义链接不会接受 HTTPS 或其他协议。</p></div><div class="form-section" data-anchor="language-validation"><div class="section-title"><h3>发布校验</h3><p>${missing.length||errors.unknown.length||errors.unsupported.length?"存在阻断项":"已通过"}</p></div>${missing.length?`<div class="help-alert danger">已选语言缺少 title/body：${esc(missing.join("、"))}</div>`:`<div class="help-alert success">已选语言的 title/body 完整。</div>`}${errors.unknown.length?`<div class="help-alert danger">未知占位符：${esc(errors.unknown.join("、"))}</div>`:""}${errors.unsupported.length?`<div class="help-alert danger">当前触发无法提供：${esc(errors.unsupported.join("、"))}</div>`:""}</div>`}

export function openLanguageDrawer({onClose}={}){const root=$("#overlayRoot");root.insertAdjacentHTML("beforeend",`<div class="drawer-host is-open" id="languageDrawer" style="z-index:1400"><div class="drawer-mask" data-language-close></div><aside class="drawer" role="dialog" aria-modal="true" aria-label="编辑规则多语言内容"><header class="drawer-header"><div class="drawer-title"><h2>规则多语言内容</h2><p>${esc(appState.rule.name)} · 默认编辑语言 English · title / body KV</p></div><button class="icon-btn" data-language-close>×</button></header><div class="drawer-content">${bodyMarkup()}</div><footer class="drawer-footer"><button class="el-btn" data-language-close>取消</button><button class="el-btn el-btn--primary" data-language-save>保存多语言内容</button></footer></aside></div>`);renderAnnotations("language","规则多语言内容");wire(onClose)}
function wire(onClose){const host=$("#languageDrawer");if(!host)return;const redraw=()=>{host.querySelector(".drawer-content").innerHTML=bodyMarkup();wireBody(host,onClose)};wireBody(host,onClose);host.querySelectorAll("[data-language-close]").forEach(el=>el.addEventListener("click",()=>close(onClose)));host.querySelector("[data-language-save]").addEventListener("click",e=>{const missing=selectedMissing();const errors=selectedTokenErrors();if(missing.length||errors.unknown.length||errors.unsupported.length){showToast("发布校验未通过，请修复已选语言内容","error");return}e.currentTarget.disabled=true;e.currentTarget.textContent="保存中…";setTimeout(()=>{showToast("已保存 18 语言 KV（仅已选语言参与发布）");close(onClose)},550)})}
function wireBody(host,onClose){host.querySelectorAll("[data-locale-toggle]").forEach(el=>el.addEventListener("change",()=>{const code=el.dataset.localeToggle;if(code==="en-US")return;if(el.checked&&!appState.selectedLocales.includes(code))appState.selectedLocales.push(code);if(!el.checked)appState.selectedLocales=appState.selectedLocales.filter(x=>x!==code);host.querySelector(".drawer-content").innerHTML=bodyMarkup();wireBody(host,onClose)}));host.querySelectorAll("[data-lang]").forEach(el=>el.addEventListener("input",()=>{appState.message.values[el.dataset.lang]??={title:"",body:""};appState.message.values[el.dataset.lang][el.dataset.key]=el.value}))}
function close(onClose){const host=$("#languageDrawer");if(!host)return;host.classList.remove("is-open");setTimeout(()=>{host.remove();onClose?.()},220)}
