import {$,esc,showToast} from "./dom.js";
import {appState,productLanguageConfig,rules,supportedLanguages,notificationTopics} from "./state.js";
import {renderAnnotations} from "./annotations.js";

const clone=value=>JSON.parse(JSON.stringify(value));
const languageName=code=>supportedLanguages.find(item=>item[0]===code)?.[1]||code;
const productRules=()=>rules.filter(rule=>rule.productId===appState.selectedProductId);
const topics=()=>notificationTopics.filter(topic=>topic.productId===appState.selectedProductId);
const committed=()=>productLanguageConfig[appState.selectedProductId]??(productLanguageConfig[appState.selectedProductId]={selectedLocales:["en-US"],values:{}});
let draft=null;
function rows(){return [...topics().flatMap(topic=>[{key:`topic.${topic.id}.title`,label:`主题 · ${topic.name} · Title`,limit:100,defaultValue:topic.values?.["en-US"]?.title||""},{key:`topic.${topic.id}.body`,label:`主题 · ${topic.name} · Body`,limit:200,defaultValue:topic.values?.["en-US"]?.body||""}]),...productRules().flatMap(rule=>rule.notificationTopicId?[{key:`rule.${rule.id}.itemLabel`,label:`规则 · ${rule.name} · 提醒项`,limit:100,defaultValue:rule.itemLabel||""}]:[{key:`rule.${rule.id}.title`,label:`规则 · ${rule.name} · Title`,limit:100,defaultValue:rule.title||""},{key:`rule.${rule.id}.body`,label:`规则 · ${rule.name} · Body`,limit:200,defaultValue:rule.body||""}])];}
function valuesFor(row){return draft.values[row.key]??(draft.values[row.key]={"en-US":row.defaultValue})}
function choices(){return `<div class="locale-grid" data-anchor="language-selection">${supportedLanguages.map(([code,name])=>{const checked=draft.selectedLocales.includes(code),locked=code==="en-US";return `<label class="locale-option ${checked?"selected":""}"><input type="checkbox" data-locale="${esc(code)}" ${checked?"checked":""} ${locked?"disabled":""}><span><strong>${esc(name)}</strong><small>${esc(code)}${locked?" · 默认":""}</small></span></label>`}).join("")}</div>`}
function matrix(){const entries=rows();return `<div class="matrix-wrap" data-anchor="product-language-matrix"><table class="lang-matrix product-language-matrix"><thead><tr><th style="min-width:260px">输入项</th>${draft.selectedLocales.map(code=>`<th style="min-width:220px">${esc(languageName(code))}<small>${esc(code)}</small></th>`).join("")}</tr></thead><tbody>${entries.map(row=>`<tr><td><strong>${esc(row.label)}</strong><div class="secondary-cell">${esc(row.key)} · 最多 ${row.limit} 字符</div></td>${draft.selectedLocales.map(code=>`<td><textarea data-language-key="${esc(row.key)}" data-language-locale="${esc(code)}" maxlength="${row.limit}" placeholder="${esc(languageName(code))}">${esc(valuesFor(row)[code]||"")}</textarea></td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function issues(){return rows().flatMap(row=>draft.selectedLocales.map(code=>{const value=valuesFor(row)[code]||"";return !value.trim()?`${row.label} · ${languageName(code)} 未填写`:value.length>row.limit?`${row.label} · ${languageName(code)} 超过 ${row.limit} 字符`:null}).filter(Boolean))}
function body(){const missing=issues();return `<div class="help-alert" data-anchor="product-language-intro"><strong>统一多语言。</strong> 主题共享文案只出现一次；加入主题的规则只维护自己的提醒项，独立规则维护自己的 Title/Body。</div><div class="form-section"><div class="section-title"><h3>选择语言</h3><p>English 必选，其他 17 个语言按需选择</p></div>${choices()}</div><div class="form-section"><div class="section-title"><h3>多语言大表</h3><p>按主题和规则的真实内容归属维护</p></div><div class="inline-actions"><button class="el-btn" data-export-language>导出当前草稿</button><span class="secondary-cell">取消不会保存语言选择或内容。</span></div>${matrix()}</div><div class="form-section" data-anchor="product-language-validation"><div class="section-title"><h3>待补全提醒</h3><p>${missing.length?"保存后仍可继续补全":"已选语言内容已补全"}</p></div><div class="help-alert ${missing.length?"warning":"success"}">${missing.length?`建议补全：${missing.slice(0,4).map(esc).join("；")}${missing.length>4?`；还有 ${missing.length-4} 项`:""}`:"当前产品已选语言的内容都已填写。"}</div></div>`}
function shell(){return `<div class="drawer-host is-open" id="languageDrawer" style="z-index:1400"><div class="drawer-mask" data-language-cancel></div><aside class="drawer"><header class="drawer-header"><div class="drawer-title"><h2>统一配置多语言</h2><p>当前产品 · 主题和规则共用一张 KV 大表</p></div><button class="icon-btn" data-language-cancel>×</button></header><div class="drawer-main"><div class="drawer-body"><section class="drawer-content">${body()}</section></div></div><footer class="drawer-footer"><span class="save-hint">取消不保存；未填写内容可后续补全</span><div class="footer-actions"><button class="el-btn" data-language-cancel>取消</button><button class="el-btn el-btn--primary" data-language-save>保存</button></div></footer></aside></div>`}
function close(onClose){draft=null;$("#languageDrawer")?.remove();onClose?.()}
function exportDraft(){const list=rows(),text=[["input key",...draft.selectedLocales.map(languageName)],...list.map(row=>[row.key,...draft.selectedLocales.map(code=>valuesFor(row)[code]||"")])].map(line=>line.map(value=>String(value).replace(/\t/g," ")).join("\t")).join("\n"),blob=new Blob(["\uFEFF",text],{type:"text/tab-separated-values;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${appState.selectedProductId}-push-language-draft.tsv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);showToast("已导出当前草稿")}
function applyValues(){Object.assign(committed(),clone(draft));rows().forEach(row=>{const values=valuesFor(row),[kind,id,field]=row.key.split(".");if(kind==="topic"){const topic=notificationTopics.find(item=>item.id===id);if(topic){topic.values??={};topic.values["en-US"]??={};topic.values["en-US"][field]=values["en-US"]||""}}else{const rule=rules.find(item=>item.id===id);if(rule){if(field==="itemLabel")rule.itemLabel=values["en-US"]||"";else rule[field]=values["en-US"]||""}}});productRules().forEach(rule=>rule.languages=String(draft.selectedLocales.length))}
function wire(onClose){const host=$("#languageDrawer");host.querySelectorAll("[data-language-cancel]").forEach(item=>item.onclick=()=>close(onClose));host.querySelectorAll("[data-locale]").forEach(input=>input.onchange=()=>{const code=input.dataset.locale;draft.selectedLocales=input.checked?[...new Set([...draft.selectedLocales,code])]:draft.selectedLocales.filter(value=>value!==code);host.outerHTML=shell();wire(onClose)});host.querySelectorAll("[data-language-key]").forEach(input=>input.oninput=()=>{const row=rows().find(item=>item.key===input.dataset.languageKey);if(row)valuesFor(row)[input.dataset.languageLocale]=input.value});host.querySelector("[data-export-language]")?.addEventListener("click",exportDraft);host.querySelector("[data-language-save]")?.addEventListener("click",()=>{applyValues();showToast("产品多语言已保存，可后续补全内容");close(onClose)})}
export function openProductLanguageDrawer({onClose}={}){draft=clone(committed());draft.values??={};$("#overlayRoot").insertAdjacentHTML("beforeend",shell());renderAnnotations("language","统一配置多语言");wire(onClose)}
