import {$,$$,esc,showToast} from "./dom.js";
import {appState,productLanguageConfig,rules,supportedLanguages} from "./state.js";
import {renderAnnotations} from "./annotations.js";

const languageName=code=>supportedLanguages.find(item=>item[0]===code)?.[1]||code;
const productRules=()=>rules.filter(rule=>rule.productId===appState.selectedProductId);
const config=()=>productLanguageConfig[appState.selectedProductId]??(productLanguageConfig[appState.selectedProductId]={selectedLocales:["en-US"],values:{}});
const rows=()=>productRules().flatMap(rule=>[{key:`${rule.id}.title`,label:`${rule.name} · Title`,limit:100,defaultValue:rule.title},{key:`${rule.id}.body`,label:`${rule.name} · Body`,limit:200,defaultValue:"Your device needs attention."}]);
function valuesFor(row){const values=config().values??(config().values={});return values[row.key]??(values[row.key]={"en-US":row.defaultValue})}
function selected(){return config().selectedLocales}
function validate(){const issues=[];rows().forEach(row=>selected().forEach(code=>{const value=valuesFor(row)[code]||"";if(!value.trim())issues.push(`${row.label} · ${languageName(code)} 未填写`);else if(value.length>row.limit)issues.push(`${row.label} · ${languageName(code)} 超过 ${row.limit} 字符`)}));return issues}
function localeChoices(){return `<div class="locale-grid" data-anchor="language-selection">${supportedLanguages.map(([code,name])=>{const checked=selected().includes(code),locked=code==="en-US";return `<label class="locale-option ${checked?"selected":""}"><input type="checkbox" data-locale="${esc(code)}" ${checked?"checked":""} ${locked?"disabled":""}><span><strong>${esc(name)}</strong><small>${esc(code)}${locked?" · 默认":""}</small></span></label>`}).join("")}</div>`}
function matrix(){return `<div class="matrix-wrap" data-anchor="product-language-matrix"><table class="lang-matrix product-language-matrix"><thead><tr><th style="min-width:220px">输入项</th>${selected().map(code=>`<th style="min-width:220px">${esc(languageName(code))}<small>${esc(code)}</small></th>`).join("")}</tr></thead><tbody>${rows().map(row=>`<tr><td><strong>${esc(row.label)}</strong><div class="secondary-cell">${esc(row.key)} · 最多 ${row.limit} 字符</div></td>${selected().map(code=>`<td><textarea data-value-key="${esc(row.key)}" data-locale-value="${esc(code)}" maxlength="${row.limit}" placeholder="${esc(languageName(code))}">${esc(valuesFor(row)[code]||"")}</textarea></td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function body(){const issues=validate();return `<div class="help-alert" data-anchor="product-language-intro"><strong>统一多语言。</strong> 当前产品的所有规则都在这一张表中维护。English 默认选中；需要哪些语言，就勾选哪些语言。</div><div class="form-section"><div class="section-title"><h3>选择语言</h3><p>English 必选，其他 17 个语言按需选择</p></div>${localeChoices()}</div><div class="form-section"><div class="section-title"><h3>多语言大表</h3><p>每行一个输入项，每列一种语言</p></div><div class="inline-actions"><button class="el-btn" data-export-language>导出大表</button><span class="secondary-cell">导出后可在表格软件中继续查看或整理。</span></div>${matrix()}</div><div class="form-section" data-anchor="product-language-validation"><div class="section-title"><h3>保存检查</h3><p>${issues.length?"还有未填写内容":"已可以保存"}</p></div>${issues.length?`<div class="help-alert danger">${issues.slice(0,4).map(esc).join("；")}${issues.length>4?`；还有 ${issues.length-4} 项`:""}</div>`:'<div class="help-alert success">已选语言的所有输入项都已填写。</div>'}</div>`}
function drawer(){return `<div class="drawer-host is-open" id="languageDrawer" style="z-index:1400"><div class="drawer-mask" data-language-close></div><aside class="drawer" role="dialog" aria-modal="true" aria-label="统一配置多语言"><header class="drawer-header"><div class="drawer-title"><h2>统一配置多语言</h2><p>当前产品 · 所有推送规则共用一张 KV 大表</p></div><button class="icon-btn" data-language-close>×</button></header><div class="drawer-main"><div class="drawer-body"><section class="drawer-content">${body()}</section></div></div><footer class="drawer-footer"><span class="save-hint">仅校验已选语言</span><div class="footer-actions"><button class="el-btn" data-language-close>取消</button><button class="el-btn el-btn--primary" data-language-save>保存</button></div></footer></aside></div>`}
function exportTable(){const header=["input key",...selected().map(languageName)],content=[header,...rows().map(row=>[row.key,...selected().map(code=>valuesFor(row)[code]||"")])].map(line=>line.map(value=>String(value).replace(/\t/g," ")).join("\t")).join("\n"),blob=new Blob(["\uFEFF",content],{type:"text/tab-separated-values;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${appState.selectedProductId}-push-language.tsv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);showToast("已导出多语言大表")}
function rerender(){const host=$("#languageDrawer");if(!host)return;host.outerHTML=drawer();wire()}
function close(onClose){const host=$("#languageDrawer");if(!host)return;host.remove();onClose?.()}
function wire(onClose){const host=$("#languageDrawer");if(!host)return;host.querySelectorAll("[data-language-close]").forEach(item=>item.onclick=()=>close(onClose));host.querySelectorAll("[data-locale]").forEach(input=>input.onchange=()=>{const code=input.dataset.locale;config().selectedLocales=input.checked?[...new Set([...selected(),code])]:selected().filter(value=>value!==code);rerender()});host.querySelectorAll("[data-value-key]").forEach(input=>input.oninput=()=>{const row=rows().find(item=>item.key===input.dataset.valueKey);if(row)valuesFor(row)[input.dataset.localeValue]=input.value});host.querySelector("[data-export-language]")?.addEventListener("click",exportTable);host.querySelector("[data-language-save]")?.addEventListener("click",()=>{const issues=validate();if(issues.length){showToast("请补全已选语言的内容","error");return}productRules().forEach(rule=>rule.languages=String(selected().length));showToast("产品多语言已保存");close(onClose)})}
export function openProductLanguageDrawer({onClose}={}){$("#overlayRoot").insertAdjacentHTML("beforeend",drawer());renderAnnotations("language","统一配置多语言");wire(onClose)}

const ruleRows=rule=>[
  {key:`${rule.id}.title`,label:"Title",limit:100,defaultValue:rule.title},
  {key:`${rule.id}.body`,label:"Body",limit:200,defaultValue:"Your device needs attention."}
];
function ruleIssues(rule){const issues=[];ruleRows(rule).forEach(row=>selected().forEach(code=>{const value=valuesFor(row)[code]||"";if(!value.trim())issues.push(`${row.label} · ${languageName(code)} 未填写`);else if(value.length>row.limit)issues.push(`${row.label} · ${languageName(code)} 超过 ${row.limit} 字符`)}));return issues}
function ruleMatrix(rule){return `<div class="matrix-wrap" data-anchor="rule-language-matrix"><table class="lang-matrix rule-language-matrix"><thead><tr><th style="min-width:148px">输入项</th>${selected().map(code=>`<th style="min-width:230px">${esc(languageName(code))}<small>${esc(code)}</small></th>`).join("")}</tr></thead><tbody>${ruleRows(rule).map(row=>`<tr><td><strong>${esc(row.label)}</strong><div class="secondary-cell">最多 ${row.limit} 字符</div></td>${selected().map(code=>`<td><textarea data-rule-value-key="${esc(row.key)}" data-rule-locale-value="${esc(code)}" maxlength="${row.limit}" placeholder="${esc(languageName(code))}">${esc(valuesFor(row)[code]||"")}</textarea></td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function ruleBody(rule){const issues=ruleIssues(rule);return `<div class="help-alert" data-anchor="rule-language-intro"><strong>仅编辑当前规则。</strong> ${esc(rule.name)} 的语言内容在这里维护；语言范围由当前产品的「统一多语言」决定。</div><div class="form-section"><div class="section-title"><h3>多语言内容</h3><p>每行一个输入项，每列一种已选语言</p></div>${ruleMatrix(rule)}</div><div class="form-section" data-anchor="rule-language-validation"><div class="section-title"><h3>保存检查</h3><p>${issues.length?"还有未填写内容":"已可以保存"}</p></div>${issues.length?`<div class="help-alert danger">${issues.slice(0,4).map(esc).join("；")}${issues.length>4?`；还有 ${issues.length-4} 项`:""}</div>`:'<div class="help-alert success">当前规则已选语言的内容都已填写。</div>'}</div>`}
function ruleDrawer(rule){return `<div class="drawer-host is-open" id="ruleLanguageDrawer" style="z-index:1450"><div class="drawer-mask" data-rule-language-close></div><aside class="drawer" role="dialog" aria-modal="true" aria-label="编辑规则多语言"><header class="drawer-header"><div class="drawer-title"><h2>编辑多语言</h2><p>${esc(rule.name)} · 仅此规则</p></div><button class="icon-btn" data-rule-language-close>×</button></header><div class="drawer-main"><div class="drawer-body"><section class="drawer-content">${ruleBody(rule)}</section></div></div><footer class="drawer-footer"><span class="save-hint">仅校验当前产品已选语言</span><div class="footer-actions"><button class="el-btn" data-rule-language-close>取消</button><button class="el-btn el-btn--primary" data-rule-language-save>保存</button></div></footer></aside></div>`}
function closeRuleLanguage(onClose){const host=$("#ruleLanguageDrawer");if(!host)return;host.remove();onClose?.()}
function wireRuleLanguage(rule,onClose){const host=$("#ruleLanguageDrawer");if(!host)return;host.querySelectorAll("[data-rule-language-close]").forEach(item=>item.onclick=()=>closeRuleLanguage(onClose));host.querySelectorAll("[data-rule-value-key]").forEach(input=>input.oninput=()=>{const row=ruleRows(rule).find(item=>item.key===input.dataset.ruleValueKey);if(row)valuesFor(row)[input.dataset.ruleLocaleValue]=input.value});host.querySelector("[data-rule-language-save]")?.addEventListener("click",()=>{const issues=ruleIssues(rule);if(issues.length){showToast("请补全已选语言的内容","error");return}const title=valuesFor(ruleRows(rule)[0])["en-US"];if(title)rule.title=title;rule.languages=String(selected().length);showToast("规则多语言已保存");closeRuleLanguage(onClose)})}
export function openRuleLanguageDrawer(rule,{onClose}={}){if(!rule)return;$("#overlayRoot").insertAdjacentHTML("beforeend",ruleDrawer(rule));renderAnnotations("ruleLanguage",`多语言 · ${rule.name}`);wireRuleLanguage(rule,onClose)}
