import {$,esc,showToast} from "./dom.js";
import {appState,products,productSources,rules,supportedLanguages,newRule} from "./state.js";
import {openLanguageDrawer} from "./language-editor.js";
import {renderAnnotations} from "./annotations.js";

const steps=[[1,"触发与接收者","既有产品来源与绑定用户"],[2,"投递与发布","逐条或后续丢弃"],[3,"基础信息与消息","English 与 KV 快速导入"]];
const product=()=>products.find(item=>item.id===appState.selectedProductId)||products[0];
const sources=()=>productSources[appState.selectedProductId]||{properties:[],countdowns:[],consumables:[]};
const languageName=code=>supportedLanguages.find(item=>item[0]===code)?.[1]||code;
const mode=()=>appState.rule.reminderMode;

function stepNav(){return `<nav class="step-nav" id="ruleStepNav" data-anchor="step-nav"><div class="step-progress"><span>P0 规则配置</span><strong>步骤 ${appState.ruleStep} / 3</strong></div><ol class="step-list">${steps.map(([number,title,subtitle],index)=>`<li class="step-slot"><button class="step-item ${number===appState.ruleStep?"active":""} ${number<appState.ruleStep?"is-complete":""}" data-step="${number}"><span class="step-index">${number<appState.ruleStep?"✓":number}</span><span class="step-copy"><strong>${title}</strong><small>${subtitle}</small></span></button>${index<2?'<span class="step-connector"></span>':""}</li>`).join("")}</ol></nav>`}

function sourceCapability(source,kind){if(!source)return `<div class="help-alert warning">当前产品暂无可用${kind}来源，不能发布。</div>`;const ready=source.deviceCapability==="verified"&&(kind!=="云计时器"||source.cycleContract==="verified");return `<div class="help-alert ${ready?"success":"warning"}"><strong>${ready?"来源可用":"待来源验收"}</strong> · ${kind}必须提供真实 deviceId${kind==="云计时器"?" 和稳定周期标识":""}。来源异常时系统不投递并记录审计。</div>`}

function trigger(){const rule=appState.rule,source=sources(),property=source.properties.find(item=>item.id===rule.propertyId)||source.properties[0];const choices=[["device","设备触发","属性满足条件时触发"],["cloud","云端触发","计时器剩余时长命中阈值"],["consumable","耗材触发","不足或耗尽时触发"]];let detail="";
  if(rule.triggerType==="device")detail=`<div class="form-grid"><label class="form-row"><span class="form-label"><i class="required">*</i>设备属性</span><select class="el-select" data-rule="propertyId">${source.properties.map(item=>`<option value="${item.id}" ${item.id===rule.propertyId?"selected":""}>${item.name}${item.unit?`（${item.unit}）`:""}</option>`).join("")}</select></label><label class="form-row"><span class="form-label"><i class="required">*</i>运算符</span><select class="el-select" data-rule="operator">${(property?.operators||[]).map(item=>`<option ${item===rule.operator?"selected":""}>${item}</option>`).join("")}</select></label><label class="form-row full"><span class="form-label"><i class="required">*</i>条件值</span>${property?.type==="enum"?`<select class="el-select" data-rule="propertyValue">${property.options.map(item=>`<option ${item===rule.propertyValue?"selected":""}>${item}</option>`).join("")}</select>`:property?.type==="boolean"?`<select class="el-select" data-rule="propertyValue"><option value="true" ${rule.propertyValue==="true"?"selected":""}>true</option><option value="false" ${rule.propertyValue==="false"?"selected":""}>false</option></select>`:`<input class="el-input" data-rule="propertyValue" value="${esc(rule.propertyValue)}" placeholder="例如 ${property?.example||"1"}">`}<p class="form-help">触发逻辑：if（${esc(property?.name||"属性")} ${esc(rule.operator)} ${esc(rule.propertyValue)}${property?.unit?` ${property.unit}`:""}）。</p></label></div>`;
  if(rule.triggerType==="cloud"){const timer=source.countdowns.find(item=>item.id===rule.cloudCountdownId)||source.countdowns[0],limit=timer?.durationMinutes;detail=`<div class="form-grid"><label class="form-row"><span class="form-label"><i class="required">*</i>云计时器</span><select class="el-select" data-rule="cloudCountdownId">${source.countdowns.map(item=>`<option value="${item.id}" ${item.id===rule.cloudCountdownId?"selected":""}>${item.name}</option>`).join("")||'<option value="">当前产品暂无云计时器</option>'}</select></label><label class="form-row"><span class="form-label"><i class="required">*</i>剩余时长阈值</span><div class="threshold-control"><input class="el-input" type="number" min="0" step="1" ${Number.isFinite(limit)?`max="${limit}"`:""} data-rule="cloudThresholdMinutes" value="${esc(rule.cloudThresholdMinutes)}"><span>分钟</span></div><p class="form-help">触发条件：剩余时长 ≤ ${esc(rule.cloudThresholdMinutes||"未设置")} 分钟${Number.isFinite(limit)?`；当前周期上限 ${limit} 分钟`:""}。</p></label></div><div class="timeline" data-anchor="cloud-source"><div class="timeline-title">云端触发由现有计时器能力提供</div><div class="timeline-row"><span class="timeline-dot active"></span><strong>首次命中阈值</strong><small>本周期只触发一次</small><span>离开阈值或自动 reset 后由系统重新 arm</span></div></div>${sourceCapability(timer,"云计时器")}`}
  if(rule.triggerType==="consumable"){const consumable=source.consumables.find(item=>item.id===rule.consumableId);detail=`<div class="form-grid"><label class="form-row"><span class="form-label"><i class="required">*</i>耗材项</span><select class="el-select" data-rule="consumableId">${source.consumables.map(item=>`<option value="${item.id}" ${item.id===rule.consumableId?"selected":""}>${item.name}</option>`).join("")||'<option value="">当前产品暂无配置耗材</option>'}</select></label><label class="form-row"><span class="form-label"><i class="required">*</i>触发项</span><select class="el-select" data-rule="consumableEvent"><option value="low" ${rule.consumableEvent==="low"?"selected":""}>不足</option><option value="empty" ${rule.consumableEvent==="empty"?"selected":""}>耗尽</option></select></label></div>${sourceCapability(consumable,"耗材")}`}
  return `<div class="form-section" data-anchor="trigger-source"><div class="section-title"><h3>触发源</h3><p>仅使用当前产品已配置来源</p></div><div class="radio-row">${choices.map(([value,title,subtitle])=>`<label class="choice-card ${rule.triggerType===value?"selected":""}"><input type="radio" name="trigger" value="${value}" ${rule.triggerType===value?"checked":""}><span class="choice-copy"><strong>${title}</strong><small>${subtitle}</small></span></label>`).join("")}</div><div class="trigger-detail">${detail}</div></div><div class="form-section" data-anchor="recipient-resolution"><div class="section-title"><h3>接收者解析</h3><p>系统固定解析</p></div><div class="help-alert">每次触发必须落到真实 <code>deviceId</code>，最终接收者 = <code>BindUsers(deviceId)</code>。无绑定用户时正常抑制并审计；不提供用户名单、用户筛选或 B 端接收人。</div></div>`}

function delivery(){const rule=appState.rule,discard=mode()==="discard";return `<div class="form-section" data-anchor="delivery-mode"><div class="section-title"><h3>提醒模式</h3><p>首期只提供两种投递方式</p></div><div class="radio-row"><label class="choice-card ${!discard?"selected":""}"><input type="radio" name="mode" value="each" ${!discard?"checked":""}><span class="choice-copy"><strong>逐条发送</strong><small>每个唯一事件立即发送</small></span></label><label class="choice-card ${discard?"selected":""}"><input type="radio" name="mode" value="discard" ${discard?"checked":""}><span class="choice-copy"><strong>后续丢弃</strong><small>窗口首条发送，后续事件抑制</small></span></label></div>${discard?`<label class="form-row" style="margin-top:14px"><span class="form-label"><i class="required">*</i>最小发送间隔</span><input class="el-input" type="number" min="5" max="10080" data-rule="minIntervalMinutes" value="${esc(rule.minIntervalMinutes)}"><p class="form-help">5 分钟至 7 天。窗口从首条实际发送开始，窗口内事件仅记录 suppressed。</p></label>`:""}</div><div class="form-section" data-anchor="frequency-timeline"><div class="section-title"><h3>投递时间线</h3><p>${discard?"后续丢弃":"逐条发送"}</p></div><div class="timeline"><div class="timeline-row"><span class="timeline-dot active"></span><strong>唯一事件到达</strong><small>校验 deviceId 与去重键</small><span>${discard?"首条立即发送并开启窗口":"立即发送"}</span></div>${discard?`<div class="timeline-row"><span class="timeline-dot"></span><strong>窗口内后续事件</strong><small>suppressed</small><span>不重复推送，保留审计记录</span></div>`:""}</div><p class="form-help">后续版本才支持合并发送、状态切换、优先级和熔断策略配置。</p></div><div class="form-section" data-anchor="validation"><div class="section-title"><h3>发布校验</h3><p>来源、投递参数与内容完整性</p></div>${validation()}</div>`}

function basic(){const rule=appState.rule,message=appState.message.values["en-US"],link=product().presetLinks.find(item=>item.id===rule.presetLinkId)||product().presetLinks[0];return `<div class="form-section"><div class="section-title"><h3>基础信息</h3><p>规则归属当前产品</p></div><div class="form-grid"><label class="form-row full"><span class="form-label"><i class="required">*</i>规则名称</span><input class="el-input" data-rule="name" value="${esc(rule.name)}" placeholder="例如：储奶量过高提醒"></label><label class="form-row"><span class="form-label">当前产品</span><div class="readonly-field">${esc(product().name)} · ${esc(product().id)}</div></label><label class="form-row"><span class="form-label">消息分类</span><select class="el-select" data-rule="category">${["安全","维护","耗材","通知"].map(item=>`<option ${item===rule.category?"selected":""}>${item}</option>`).join("")}</select></label></div></div><div class="form-section" data-anchor="message-editor"><div class="section-title"><h3>推送消息 · English</h3><p>English 是默认 fallback</p></div><label class="form-row full"><span class="form-label"><i class="required">*</i>Title</span><input class="el-input" data-content="title" maxlength="100" value="${esc(message.title)}"></label><label class="form-row full"><span class="form-label"><i class="required">*</i>Body</span><textarea class="el-textarea" data-content="body" maxlength="200">${esc(message.body)}</textarea></label></div><div class="form-section" data-anchor="jump-mode"><div class="section-title"><h3>跳转页面</h3><p>首期只支持产品预设页面</p></div><div class="radio-row"><label><input type="radio" name="link" value="none" ${rule.linkMode==="none"?"checked":""}> 不跳转</label><label><input type="radio" name="link" value="preset" ${rule.linkMode!=="none"?"checked":""}> 产品预设页面</label></div>${rule.linkMode!=="none"?`<select class="el-select" data-preset>${product().presetLinks.map(item=>`<option value="${item.id}" ${item.id===rule.presetLinkId?"selected":""}>${item.label} · ${item.uri}</option>`).join("")}</select>`:""}</div><div class="form-section" data-anchor="language-entry"><div class="section-title"><h3>多语言 KV</h3><p>已导入 ${appState.selectedLocales.length} 个语言</p></div><div class="help-alert success">通过粘贴 <code>locale / title / body</code> 三列快速导入。当前语言：${appState.selectedLocales.map(languageName).join("、")}。</div><button class="el-btn" data-language>粘贴导入 / 编辑 KV</button><p class="form-help">只校验 KV 矩阵中存在的语言；文件导入导出和翻译辅助属于后续版本。</p></div>`}

function validation(){const rule=appState.rule,source=rule.triggerType==="cloud"?sources().countdowns.find(item=>item.id===rule.cloudCountdownId):rule.triggerType==="consumable"?sources().consumables.find(item=>item.id===rule.consumableId):null,property=sources().properties.find(item=>item.id===rule.propertyId);const contentOk=appState.selectedLocales.every(code=>{const value=appState.message.values[code]||{};return value.title?.trim()&&value.body?.trim()&&value.title.length<=100&&value.body.length<=200});const deviceOk=rule.triggerType!=="device"||!!property&&property.operators.includes(rule.operator)&&String(rule.propertyValue||"").trim()!=="";const cloudValue=Number(rule.cloudThresholdMinutes);const cloudOk=rule.triggerType!=="cloud"||!!source&&Number.isInteger(cloudValue)&&cloudValue>=0&&cloudValue<=source.durationMinutes&&source.deviceCapability==="verified"&&source.cycleContract==="verified";const consumableOk=rule.triggerType!=="consumable"||!!source&&source.deviceCapability==="verified";const intervalOk=mode()==="each"||(+rule.minIntervalMinutes>=5&&+rule.minIntervalMinutes<=10080);const checks=[[!!rule.name.trim(),"规则名称"],[deviceOk,"设备条件"],[cloudOk,"云端计时器与阈值"],[consumableOk,"耗材来源"],[contentOk,"English 与已导入 KV 内容"],[intervalOk,"后续丢弃的最小发送间隔"]];return `<div class="validation-list">${checks.map(([ok,text])=>`<div class="validation-item ${ok?"":"validation-fail"}"><span>${ok?"✓":"!"} ${text}</span><span class="el-tag el-tag--${ok?"success":"danger"} is-plain">${ok?"通过":"阻断"}</span></div>`).join("")}</div>`}

function content(){return appState.ruleStep===1?trigger():appState.ruleStep===2?delivery():basic()}
function shell(){return `<div class="drawer-host is-open" id="ruleDrawer"><div class="drawer-mask" data-close></div><aside class="drawer"><header class="drawer-header"><div class="drawer-title"><h2>${appState.editingRule?"编辑":"新建"}推送规则</h2><p>${esc(product().name)} · P0 规则闭环</p></div><button class="icon-btn" data-close>×</button></header><div class="drawer-main">${stepNav()}<div class="drawer-body"><section class="drawer-content" id="ruleStepContent">${content()}</section></div></div><footer class="drawer-footer"><span class="save-hint">保存后按当前产品生效</span><div class="footer-actions"><button class="el-btn" data-draft>保存草稿</button><button class="el-btn" data-prev ${appState.ruleStep===1?"disabled":""}>上一步</button>${appState.ruleStep<3?'<button class="el-btn el-btn--primary" data-next>下一步</button>':'<button class="el-btn el-btn--primary" data-publish>保存并启用</button>'}</div></footer></aside></div>`}
function rerender(){const host=$("#ruleDrawer");if(!host)return;host.outerHTML=shell();wire();renderAnnotations(`rule${appState.ruleStep}`,`规则配置 · 步骤 ${appState.ruleStep}/3`)}
function triggerLabel(){const rule=appState.rule;if(rule.triggerType==="device"){const property=sources().properties.find(item=>item.id===rule.propertyId);return `设备：${property?.name||"属性"} ${rule.operator} ${rule.propertyValue}${property?.unit?` ${property.unit}`:""}`}if(rule.triggerType==="cloud"){const timer=sources().countdowns.find(item=>item.id===rule.cloudCountdownId);return `云端：${timer?.name||"计时器"} ≤ ${rule.cloudThresholdMinutes} 分钟`}const item=sources().consumables.find(value=>value.id===rule.consumableId);return `耗材：${item?.name||"耗材"}${rule.consumableEvent==="empty"?"耗尽":"不足"}`}
function save(status){const rule=appState.rule;const row={id:rule.id||`R-${2050+rules.length}`,productId:appState.selectedProductId,name:rule.name,product:product().name,category:rule.category,trigger:triggerLabel(),title:appState.message.values["en-US"].title,languages:String(appState.selectedLocales.length),strategy:mode()==="each"?"逐条发送":`后续丢弃 · ${rule.minIntervalMinutes} 分钟`,status,updated:"2026-08-05 15:30",triggerType:rule.triggerType,propertyId:rule.propertyId,operator:rule.operator,propertyValue:rule.propertyValue,cloudCountdownId:rule.cloudCountdownId,cloudThresholdMinutes:rule.cloudThresholdMinutes,consumableId:rule.consumableId,consumableEvent:rule.consumableEvent,reminderMode:rule.reminderMode,minIntervalMinutes:rule.minIntervalMinutes};const existing=rules.find(item=>item.id===rule.id);if(existing)Object.assign(existing,row);else rules.unshift(row);appState.rule.id=row.id;window.dispatchEvent(new Event("message-push:rule-changed"));showToast(status==="启用"?"规则已保存并启用":"规则草稿已保存");closeRuleDrawer()}
function wire(){const host=$("#ruleDrawer");host.querySelectorAll("[data-close]").forEach(item=>item.onclick=closeRuleDrawer);host.querySelectorAll("[data-step]").forEach(item=>item.onclick=()=>{appState.ruleStep=+item.dataset.step;rerender()});host.querySelectorAll("[data-rule]").forEach(item=>item.onchange=()=>{appState.rule[item.dataset.rule]=item.value;if(item.dataset.rule==="propertyId"){const next=sources().properties.find(property=>property.id===item.value);appState.rule.operator=next?.operators?.[0]||"=";appState.rule.propertyValue=next?.type==="enum"?next.options?.[0]||"":next?.type==="boolean"?"true":next?.example||""}rerender()});host.querySelectorAll("[data-content]").forEach(item=>item.oninput=()=>{appState.message.values["en-US"][item.dataset.content]=item.value});host.querySelectorAll('input[name="trigger"]').forEach(item=>item.onchange=()=>{appState.rule.triggerType=item.value;rerender()});host.querySelectorAll('input[name="mode"]').forEach(item=>item.onchange=()=>{appState.rule.reminderMode=item.value;rerender()});host.querySelectorAll('input[name="link"]').forEach(item=>item.onchange=()=>{appState.rule.linkMode=item.value;rerender()});host.querySelector("[data-preset]")?.addEventListener("change",item=>{appState.rule.presetLinkId=item.target.value});host.querySelector("[data-language]")?.addEventListener("click",()=>openLanguageDrawer({onClose:rerender}));host.querySelector("[data-prev]")?.addEventListener("click",()=>{appState.ruleStep--;rerender()});host.querySelector("[data-next]")?.addEventListener("click",()=>{appState.ruleStep++;rerender()});host.querySelector("[data-draft]")?.addEventListener("click",()=>save("草稿"));host.querySelector("[data-publish]")?.addEventListener("click",()=>{if(host.querySelectorAll(".validation-fail").length){showToast("发布校验未通过，请修复阻断项","error");return}save("启用")})}
export function openRuleDrawer({edit=false}={}){appState.editingRule=edit;appState.ruleStep=1;$("#overlayRoot").innerHTML=shell();wire();renderAnnotations("rule1","规则配置 · 步骤 1/3")}
export function closeRuleDrawer(){const host=$("#ruleDrawer");if(host)host.remove();renderAnnotations("rules","推送规则列表")}
export function resetRuleDraft(){appState.rule={...newRule(),productId:appState.selectedProductId};appState.message.values["en-US"]={title:"",body:""};appState.selectedLocales=["en-US"]}
